name: Build & Publish
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: List build artifacts
        run: ls -la build/libs

      - name: Publish mod
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.METEOROFTIMES_GITHUB_TOKEN }}
          modrinth-id: ${{ secrets.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: build/libs/*.jar